import React from 'react';

const HomePage = () => (
    <React.Fragment>
        <h1>Hello, welcome to my blog!</h1>
        <p>
            Text ..................
            Text ..................
            Text ..................
              </p>
        <p>
            Details ..................
            Details ..................
            Details ..................
    </p>
    </React.Fragment>
);

export default HomePage;